#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 09 00:00:43 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
