#Create Aeronautics Toolgun Client Settings
#Sun Jun 07 18:40:46 CDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=0.5
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=64
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=330
rotationStep=15
scalePercent=100
selectedFile=native\:mech_3.excraft
snapMode=LEGACY
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
