#Create Aeronautics Toolgun Client Settings
#Sun May 31 13:53:39 CDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=0.5
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=64
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=60
rotationStep=15
scalePercent=100
selectedFile=create_physical\:jitter_bug.nbt
snapMode=LEGACY
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
