#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 08 13:26:53 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
