# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				block_display = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.powergrid]
				cord = true
				block_wire = true
				string_light_cord = true
				hanging_wire = true
				zap_projectile = true

			[light_sources.settings.entities.block_factorys_bosses]
				ice_spike_pr = true
				dragon_guard_sword = true
				sandworm = true
				knight_mark = true
				glacial_shove = true
				cage_skelly = true
				blazing_fire_ball = true
				big_cage_skelly = true
				cage = true
				big_cage = true
				soul_knight_wither_skeleton = true
				underworld_knight = true
				flaming_skeleton_guard_fireball = true
				ice_spike_cluster = true
				fire_area = true
				flaming_skeleton_guard_sword = true
				pile_of_bones = true
				poison_spit_pr = true
				sand_column = true
				rift = true
				rift_projectile = true
				ice_spike = true
				poison_area = true
				infernal_dragon = true
				sword_wave = true
				frozen_skeleton = true
				big_rift_projectile = true
				yeti = true
				soul_shockwave = true
				soul_skeleton = true

			[light_sources.settings.entities.simulated]
				launched_plunger = true
				honey_glue = true
				contraption_diagram = true

			[light_sources.settings.entities.overpacked]
				giant_backpack = true

			[light_sources.settings.entities.createdieselgenerators]
				chemical_sprayer_projectile = true

			[light_sources.settings.entities.bits_n_bobs]
				inert_stationary_contraption = true

			[light_sources.settings.entities.aeronautics]
				propeller_bearing_contraption = true
				gust = true

			[light_sources.settings.entities.create]
				seat = true
				carriage_contraption = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.offroad]
				borehead_contraption_entity = true

			[light_sources.settings.entities.create_sa]
				drill_module = true
				vault_module = true
				flamethrower_pr = true
				brass_cube_r = true
				fan_module = true
				flamethrower_pr_2 = true
				magnet_module = true
				brass_drone = true

			[light_sources.settings.entities.corpse]
				corpse = true

			[light_sources.settings.entities.blazinghot]
				blaze_arrow = true

			[light_sources.settings.entities.artifacts]
				mimic = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
