version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
kubejs = true
gyro = true
farmersdelight = true
glow = true
molten_vents = true
more_tree_sizes = true
createpropulsion = true
create = true
aeronautics_dyeable_components = true
aeronautics = true
piglinproliferation = true
death_keeper = true
yungscavebiomes = true
simulated = true
ballastmod = true
friendsandfoes = true
rottencreatures = true
weatherdetector = true
createenchantablemachinery = true
copycats = true
minecraft = true
create_dragons_plus = true
createdieselgenerators = true
create_enchantment_industry = true
soulgravestone = true
create_sa = true
powergrid = true
bits_n_bobs = true
ftbquests = true
block_factorys_bosses = false
tracks = true
blazinghot = true
quicksand = true
create_power_loader = true
