[oreganized]
	electrum_kinetic_damage = false
	electrum_tool_powers = true
	electrum_weapon_powers = true
	electrum_armor_powers = true
	#Modifies the max uses of electrum tools and weapons. vanilla is 1561, modded is 1920
	# Default: 1920
	# Range: > 1
	electrum_max_uses = 1920
	speed_per_armor_piece = false

[copperagebackport]
	copper_armor_powers = true
	#Modifies the max uses of electrum tools and weapons. vanilla is 190, modded is 320
	# Default: 320
	# Range: > 1
	copper_max_uses = 320
